# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SUNXI) += sun50i-h616-wirenboard8-bootlet.dtb
dtb-$(CONFIG_ARCH_SUNXI) += sun50i-h616-wirenboard8xx.dtb
dtb-$(CONFIG_ARCH_SUNXI) += sun50i-h616-wirenboard843.dtb
dtb-$(CONFIG_ARCH_SUNXI) += sun50i-h616-wirenboard851.dtb
dtb-$(CONFIG_ARCH_SUNXI) += sun50i-h616-wirenboard851m.dtb

# Enables support for device-tree overlays
DTC_FLAGS_sun50i-h616-wirenboard8-bootlet := -@
DTC_FLAGS_sun50i-h616-wirenboard8xx := -@
DTC_FLAGS_sun50i-h616-wirenboard843 := -@
DTC_FLAGS_sun50i-h616-wirenboard851 := -@
DTC_FLAGS_sun50i-h616-wirenboard851m := -@
